[UI/#6] fix_고정지출 / 고정지출 목록 뷰, 고정지출 추가 뷰
MoneyMate-project/MoneyMate pull request #19
Opened 2023-10-12 05:34 UTC by binisnil

## Issue

- Resolves #6 

## Description

- 고정지출 목록 뷰 구현 완료
- 고정지출 추가 뷰 구현 완료

고정지출 목룍 뷰에 더미 넣어놨는데 안뜬다는거 보면,, 수정이 필요할 것 같은데 현재 에뮬이 안돌아가서 곤란하네요,,,

2023-10-12 09:37 UTC, 0zlrlo requested changes

2023-10-12 09:37 UTC, 0zlrlo commented on app/src/main/java/com/ssu/moneymate/ui/main/fixed/FixedAdapter.java
> +    Context context;
제가 보내준 링크 보면서 하시면 될 거 같아요!
거기에 var data = listOf() 이런 코드가 있는데 아마 추가해야 할 것 같습니다.
링크 한 번 확인해줘용!!🙂

2023-10-12 09:37 UTC, 0zlrlo commented on app/src/main/java/com/ssu/moneymate/ui/main/fixed/FixedFragment.java
> +        items.add(new FixedData("적금", 200));
아마 이걸 fragment가 아니라 adapter나 viewmodel 만들어서 하는 게 맞을 거에요!

2023-10-13 02:18 UTC, 0zlrlo commented on app/src/main/java/com/ssu/moneymate/ui/main/fixed/FixedAdapter.java
> +    Context context;
암 쏘리 가이즈

2023-10-13 03:08 UTC, merged

2023-10-13 13:27 UTC, HI-JIN2 commented on app/src/main/java/com/ssu/moneymate/ui/main/fixed/FixedFragment.java
> +        items.add(new FixedData("적금", 200));
아닌데용~!